Adds process_results/2 catch-all
pepsico-ecommerce/snowflex pull request #20
Opened 2021-06-04 18:26 UTC by kellyfelkins

Snowflex hasn't previously been used for insert queries. 

The result of an insert is a tuple like `{:updated, 2210568}` (the number is the count of records inserted.) I'm not sure why the atom is ":updated". 

Snowflex processes results with `process_results/2`.

This PR adds a catch-all `process_results` that simply returns the results.

2021-06-07 21:07 UTC, zbarnes757 commented
@kellyfelkins Thanks to @dustinfarris, the dialyzer issue should be resolved now in v0.3.3

2021-06-07 21:20 UTC, dustinfarris requested changes
please add unit tests for the updated return.  you can add a pattern match to the mock worker in [connection_test.exs](https://github.com/pepsico-ecommerce/snowflex/blob/55ad030576d6af69f2fd44b49f68695b74f7b2a2/test/snowflex/connection_test.exs#L18), e.g something like.

```exs
def handle_call({:sql_query, "dummy insert query"}, _from, state) do
  {:reply, {:ok, {:updated, 123}}, state}
end
```

2021-06-07 21:20 UTC, dustinfarris commented on lib/snowflex.ex
> +          sql_data() | {:error, term()} | {:updated, term()}
These should be `{:updated, integer()}` to match what odbc returns.

2021-06-09 23:59 UTC, zbarnes757 reviewed
LGTM but can you add your changes to `CHANGELOG.md` under the unreleased section? When I create a new release, I'll tag it with the release number.

2021-06-10 11:50 UTC, dustinfarris approved these changes
LGTM.  Thanks!

2021-06-10 16:04 UTC, merged